version: "3.9"
services:
  web:
    image: node:lts-alpine
    working_dir: /home/node/app
    restart: unless-stopped
    ports:
    - "3000:3000"
    command: yarn dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redislabs/rejson:latest"
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so
    volumes:
      - redis-data:/data

  redis_commander:
    container_name: redis-commander
    image: "rediscommander/redis-commander:latest"
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
volumes:
  redis-data:

