import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const Room: NextPage = () => {
	const router = useRouter();
	const { roomName } = router.query;
	return (
		<div className="px-16 dark:bg-slate-900">
			<Head>
				<title>Twitch clone</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</div>
	);
};

export default Room;
