import type { NextPage } from 'next';
import Head from 'next/head';
import RoomList from '../components/room-list';
import RoomForm from '../components/room-form';

const Home: NextPage = () => {
	return (
		<div className="px-16">
			<Head>
				<title>Twitch clone</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="min-h-screen dark:text-white py-16">
				<RoomForm />
				<RoomList />
			</main>
		</div>
	);
};

export default Home;
